---
title: Regularization in Manchester/fraser corpus
author: Emmi Russo
date: "`r Sys.Date()`"
output: 
  html_document:
  toc: false
number_sections: false
theme: lumen
toc_float: false
code_folding: hide
editor_options: 
  chunk_output_type: console
---

```{r setup}
library(tidyverse)
library(ggridges)

utts <- read_csv("fraser_utterance_data.csv", col_names = FALSE)
names(utts) <- c("utterance", "response", "response_time", "speaker", "responder", "utterance_time", "error", "age", "past_tense", "plural", "overlap", "source_file")

# coerce types, remove any wonky timing data
utts_clean <- utts %>%
  mutate_at(vars(age, response_time, utterance_time), as.numeric) %>%
  mutate_at(vars(error, past_tense, plural, overlap), as.logical) %>%
  filter(!((response_time < 0) & (!overlap))) %>%
  filter((-5 <= response_time) & (response_time <= 5) & (utterance_time <= 10))

kid_parent_utts <- utts_clean %>%
  filter((speaker == "CHI") & ((responder == "MOT")))

```

```{r get possible overregs}

#overreg_candidates <- kid_parent_utts %>%
  #mutate(overreg_candidate = ((past_tense | plural) & error)) %>%
  #filter(past_tense | plural)

#to_write <- overreg_candidates %>%
  #filter(overreg_candidate)

#write.csv(to_write, "fraser_overreg_candidates.csv")

fraser_manual_overregs <- read_csv("fraser_manual.csv")

fraser_manual_overregs$X1 = NULL

fraser_final <- kid_parent_utts %>%
  left_join(fraser_manual_overregs, by=c("utterance", "response")) %>%
  mutate(overreg = ifelse(is.na(overreg), F, ifelse(overreg == "T", T, F)))


fraser_final <- fraser_final %>%
  mutate(response_time = response_time.x, speaker = speaker.x, responder = responder.x, utterance_time = utterance_time.x, error = error.x, age = age.x, past_tense = past_tense.x, plural = plural.x, overlap = overlap.x, source_file = source_file.x)
  
fraser_final <- fraser_final[,c("utterance", "response", "speaker", "responder", "error", "age", "response_time", "utterance_time", "past_tense", "plural", "overreg", "overlap", "source_file")]

fraser_final <- fraser_final %>%
  mutate(error_type = ifelse(!error, "no error", ifelse(overreg, "overregularization", "other error")))

sub_data <- fraser_final %>%
  filter(past_tense | plural)

sub_lm <- lm(overlap ~ error_type + age + utterance_time, sub_data)
summary(sub_lm)

sub_data <- sub_data %>% filter(response_time > -2.5 & response_time < 2.5)

ggplot(sub_data, aes(x=response_time, y = error_type, fill=error_type)) + geom_density_ridges(alpha=0.6, aes(point_shape = error_type, point_fill = error_type), jittered_points = F) + theme_minimal(base_size = 14) + theme(axis.text.y = element_text(vjust = 0)) +
   scale_x_continuous(expand = c(0.01, 0)) +
   scale_y_discrete(expand = c(0.01, 0))



  geom_vline(xintercept=0, linetype="dotted", color="red") + theme_classic()
   + ggtitle("Fraser") + theme_classic() + ylim(0, 3.5) + xlim(-2.5, 2.5)

stats <- sub_data %>%
  group_by(error_type) %>%
  summarise(mean = mean(response_time), var = var(response_time), sd = sd(response_time), se = sd/sqrt(n()))

ggplot(stats, aes(x=error_type, y = mean, fill=error_type)) + geom_bar(stat="identity") + geom_errorbar(aes(ymin=mean-se, ymax=mean+se), width = 0.2) + theme_classic()

fraser_left_side <-  sub_data %>%
  filter(response_time < 0) %>%
  mutate(abs_rt = abs(response_time))

fraser_right_side <- sub_data %>%
  filter(response_time > 0)

lm(log(response_time) ~ error + age + utterance_time, fraser_right_side) %>%
summary()

lm(log(abs_rt) ~ error + age + utterance_time, fraser_left_side) %>%
summary()
  

ggplot(fraser_left_side, aes(x=log(abs_rt), fill=error_type)) + geom_density(alpha=.4)

ggplot(fraser_right_side, aes(x=log(response_time), fill=error_type)) + geom_density(alpha=.4)

 ggplot(sub_data, aes(x = age, y = response_time, fill = error)) + geom_smooth()



```

```{r}
nwords <- function(string, pseudo=F){
  ifelse( pseudo, 
          pattern <- "\\S+", 
          pattern <- "[[:alpha:]]+" 
        )
  str_count(string, pattern)
}

#Find attention check utts
ac_utts <- fraser_final %>%
  filter(responder=="MOT") %>%
  filter(source_file=="fraser/3-00-27b.xml") %>%
  mutate(ul=nwords(response)) %>%
  filter(ul==4)
```

