---
title: Regularization in Thomas corpus
author: Dan Yurovsky
date: "`r Sys.Date()`"
output: 
  html_document:
  toc: false
number_sections: false
theme: lumen
toc_float: false
code_folding: hide
---


```{r setup, include = FALSE}
library(tidyverse)
library(knitr)
```


```{r read_data}
eleanor_data <- read_csv("eleanor_utterance_data.csv", col_names = FALSE)
names(eleanor_data) <- c("utterance", "response", "response_time", "speaker", "responder", "utterance_time", "error", "age", "past_tense", "plural", "overlap")

eleanor_data_clean <- eleanor_data %>%
  mutate(age = as.numeric(gsub("[^0-9]", "", age)),
         response_time = as.numeric(response_time)) %>%
  mutate_at(vars(error, past_tense, plural, overlap), as.logical)

kid_data <- eleanor_data_clean %>%
  filter(speaker == "CHI") %>%
  filter(plural) %>%
  group_by(error) 

ggplot(kid_data, aes(x = response_time, fill = error)) + 
  geom_density(alpha = .2) +
  scale_x_continuous(limits = c(-5, 5))

ggplot(kid_data, aes(x = response_time, fill = overlap)) + 
  geom_density(alpha = .2) +
  scale_x_continuous(limits = c(-5, 5))

kid_data <- kid_data %>%
  mutate(wonky = (response_time < 0 & !overlap))

noiseless_kid_data <- kid_data[(!kid_data$wonky),]

test_data <- noiseless_kid_data %>%
  filter(responder == "CHI") %>%
  mutate(utterance_time = as.numeric(utterance_time),
         response_time = as.numeric(response_time)) %>%
  filter(response_time < 5, !overlap)

lm1 <- lm(response_time ~ utterance_time + error + log(age), test_data)

%>%
  group_by(error) %>%
  summarise(response_time = mean(response_time))


ggplot(noiseless_kid_data, aes(x = response_time, fill = error)) + 
  geom_density(alpha = .2) +
  scale_x_continuous(limits = c(-5, 5))

```